In [3]:
import numpy as np
a = np.random.normal(0, 1, (2, 3,4))
a

array([[[-1.1389757 ,  0.99423052,  0.39860796, -0.4813529 ],
        [-0.83740907, -0.4969092 , -0.39533956,  0.62263323],
        [ 0.50620978, -0.25378981, -1.02287008, -1.12531377]],

       [[ 0.06095411, -0.06582805,  0.70317865, -0.27652318],
        [-0.35882398,  0.99429198,  0.44343767,  2.26935362],
        [ 0.81980157,  0.90107356,  1.53090838, -1.15241571]]])

In [9]:
print(3*5**2)


75


In [33]:
a = np.ones((4,4))
b = np.ones((3,3))

a.shape[1]
a@a

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [27]:
a[0:2,1:3]
np.sum(a)

9.0

In [30]:

def conv(input_image, cnn_kernel):
    """
    input_image,cnn_kernel,均是方阵
    """
    image_size = input_image.shape[0]
    kernel_size = cnn_kernel.shape[0]
    result_size = image_size - kernel_size + 1

    result = np.ones((result_size, result_size))
    for i in range(result_size):
        for j in range(result_size):
            result[i][j] = np.sum(input_image[i:i+kernel_size,j:j+kernel_size] * cnn_kernel)
    return result
conv(a,b)

array([[9., 9.],
       [9., 9.]])

In [37]:
def pool(input_image, pool_kernel):
    """
    input_image,pool_kernel必须有特定的维数，这里确定pool_kernel维数为2*2
    """
    image_size = input_image.shape[0]
    kernel_size = pool_kernel.shape[0]
    result_size = image_size // 2  #要求必须能够整除
    print(result_size)

    result = np.ones((result_size, result_size))
    for i in range(result_size):
        for j in range(result_size):
            result[i][j] = np.sum(input_image[i:i+kernel_size,j:j+kernel_size] * pool_kernel)
    return result
c = 1/2 *np.ones((2,2))
d = np.ones((8,8))
pool(d,c)

4


array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [40]:
a = [c, c]
np.reshape(a, (1, -1))

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [51]:
a1 = [1,2,3,4,5,6,7,8,9,10, 11,12]
b1 = np.reshape(a1,(3,2,2))
c1 = np.reshape(b1,(-1,1))

In [52]:
b1

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [53]:
c1.shape

(12, 1)

In [55]:
np.reshape(c1,(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [62]:
@np.vectorize
def sigmoid(inx):
    if inx>=0:      #对sigmoid函数的优化，避免了出现极大的数据溢出
        return 1.0/(1+np.exp(-inx))
    else:
        return np.exp(inx)/(1+np.exp(inx))

a2 = np.ones((4,2))
sigmoid(a2)

array([[0.73105858, 0.73105858],
       [0.73105858, 0.73105858],
       [0.73105858, 0.73105858],
       [0.73105858, 0.73105858]])

In [59]:
help(np.matrixlib)

Help on package numpy.matrixlib in numpy:

NAME
    numpy.matrixlib - Sub-package containing the matrix class and related functions.

PACKAGE CONTENTS
    defmatrix
    setup
    tests (package)

CLASSES
    numpy.ndarray(builtins.object)
        numpy.matrix
    
    class matrix(ndarray)
     |  matrix(data, dtype=None, copy=True)
     |  
     |  matrix(data, dtype=None, copy=True)
     |  
     |  .. note:: It is no longer recommended to use this class, even for linear
     |            algebra. Instead use regular arrays. The class may be removed
     |            in the future.
     |  
     |  Returns a matrix from an array-like object, or from a string of data.
     |  A matrix is a specialized 2-D array that retains its 2-D nature
     |  through operations.  It has certain special operators, such as ``*``
     |  (matrix multiplication) and ``**`` (matrix power).
     |  
     |  Parameters
     |  ----------
     |  data : array_like or string
     |     If `data` is a strin