测试cnn网络的

In [1]:
import numpy as np

image_size = 28 # width and length
no_of_different_labels = 10 #  i.e. 0, 1, 2, 3, ..., 9
image_pixels = image_size * image_size
data_path = "data/mnist/"
train_data = np.loadtxt(data_path + "mnist_train.csv", 
                        delimiter=",")
test_data = np.loadtxt(data_path + "mnist_test.csv", 
                       delimiter=",") 
test_data[:10]

array([[7., 0., 0., ..., 0., 0., 0.],
       [2., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [9., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.],
       [9., 0., 0., ..., 0., 0., 0.]])

截取数据并对数据进行预处理

In [2]:
train_data = train_data[:800]
test_data = test_data[:200]

In [3]:
fac = 0.99 / 255
train_imgs = np.asfarray(train_data[:, 1:]) * fac + 0.01
test_imgs = np.asfarray(test_data[:, 1:]) * fac + 0.01

train_labels = np.asfarray(train_data[:, :1])
test_labels = np.asfarray(test_data[:, :1])



lr = np.arange(no_of_different_labels)

# transform labels into one hot representation
train_labels_one_hot = (lr==train_labels).astype(float)
test_labels_one_hot = (lr==test_labels).astype(float)

# we don't want zeroes and ones in the labels neither:
train_labels_one_hot[train_labels_one_hot==0] = 0.01
train_labels_one_hot[train_labels_one_hot==1] = 0.99
test_labels_one_hot[test_labels_one_hot==0] = 0.01
test_labels_one_hot[test_labels_one_hot==1] = 0.99


In [4]:
import conv_nn as cnn
import numpy as np

In [5]:

CNN = cnn.ConvNeuralNetwork(no_of_cnn_kernels=2, 
                            conv_kernel_size=9,
                            image_size=28,
                    no_of_out_nodes=10, 
                    no_of_hidden_nodes=100,
                    learning_rate = 0.1,)
    
    
for i in range(len(train_imgs)):
    CNN.train(train_imgs[i], train_labels_one_hot[i])

In [6]:
for i in range(20):
    res = CNN.run(test_imgs[i])
    print(test_labels[i], np.argmax(res), np.max(res))
    

[7.] 7 0.9116635554023473
[2.] 1 0.11485827400200038
[1.] 1 0.7768233562568687
[0.] 1 0.06422309227922894
[4.] 7 0.6224336123728589
[1.] 1 0.5765112530094165
[4.] 7 0.34555857191551526
[9.] 7 0.06875518185399551
[5.] 8 0.22170499020059597
[9.] 7 0.6291059831301437
[0.] 7 0.11996998071931132
[6.] 7 0.19532418075913197
[9.] 7 0.5668541134865906
[0.] 7 0.08356793021112338
[1.] 1 0.6427011614963102
[5.] 7 0.7401203839483678
[9.] 7 0.5027405503541454
[7.] 7 0.904293410678803
[3.] 6 0.322315172393891
[4.] 7 0.2488585852124955


In [7]:
corrects, wrongs = CNN.evaluate(train_imgs, train_labels)
print("accuracy train: ", corrects / ( corrects + wrongs))
corrects, wrongs = CNN.evaluate(test_imgs, test_labels)
print("accuracy: test", corrects / ( corrects + wrongs))

cm = CNN.confusion_matrix(train_imgs, train_labels)
print(cm)

for i in range(10):
    print("digit: ", i, "precision: ", CNN.precision(i, cm), "recall: ", CNN.recall(i, cm))

accuracy train:  0.34875
accuracy: test 0.31
[[ 0  1  5  1  0  0  0  0  0  0]
 [ 0 93  9  1  4  7  5  1  5  1]
 [ 1  0  3  0  0  2  2  0  1  0]
 [ 8  0  0 20  3  6  0  0  0  0]
 [ 6  1 10  2  9  3  1  1  7  0]
 [ 1  0  1  2  1  5  1  1  1  0]
 [ 7  1 14  1 13 10 57  0  7 10]
 [31  1 27 32 39 26  4 83 42 70]
 [11  1  8  6  9  7  2  0  8  2]
 [14  0  4  8  3  6  1  0  2  1]]
digit:  0 precision:  0.0 recall:  0.0
digit:  1 precision:  0.9489795918367347 recall:  0.7380952380952381
digit:  2 precision:  0.037037037037037035 recall:  0.3333333333333333
digit:  3 precision:  0.273972602739726 recall:  0.5405405405405406
digit:  4 precision:  0.1111111111111111 recall:  0.225
digit:  5 precision:  0.06944444444444445 recall:  0.38461538461538464
digit:  6 precision:  0.7808219178082192 recall:  0.475
digit:  7 precision:  0.9651162790697675 recall:  0.23380281690140844
digit:  8 precision:  0.1095890410958904 recall:  0.14814814814814814
digit:  9 precision:  0.011904761904761904 recall:  0.

In [12]:
epochs = 100


CNN2 = cnn.ConvNeuralNetwork(no_of_cnn_kernels=4, 
                            conv_kernel_size=9,
                            image_size=28,
                    no_of_out_nodes=10, 
                    no_of_hidden_nodes=100,
                    learning_rate = 0.1,)
    

for epoch in range(epochs):  
    print("epoch: ", epoch)
    for i in range(len(train_imgs)):
        
        CNN2.train(train_imgs[i], train_labels_one_hot[i])
  
    corrects, wrongs = CNN2.evaluate(train_imgs, train_labels)
    print("accuracy train: ", corrects / ( corrects + wrongs))
    corrects, wrongs = CNN2.evaluate(test_imgs, test_labels)
    print("accuracy: test", corrects / ( corrects + wrongs))

epoch:  0
accuracy train:  0.09125
accuracy: test 0.075
epoch:  1
accuracy train:  0.0925
accuracy: test 0.085
epoch:  2
accuracy train:  0.09125
accuracy: test 0.08
epoch:  3
accuracy train:  0.09375
accuracy: test 0.055
epoch:  4
accuracy train:  0.25875
accuracy: test 0.21
epoch:  5
accuracy train:  0.31375
accuracy: test 0.28
epoch:  6
accuracy train:  0.35125
accuracy: test 0.3
epoch:  7
accuracy train:  0.35875
accuracy: test 0.285
epoch:  8
accuracy train:  0.36625
accuracy: test 0.3
epoch:  9
accuracy train:  0.38625
accuracy: test 0.285
epoch:  10
accuracy train:  0.4175
accuracy: test 0.34
epoch:  11
accuracy train:  0.4125
accuracy: test 0.345
epoch:  12
accuracy train:  0.435
accuracy: test 0.36
epoch:  13
accuracy train:  0.445
accuracy: test 0.35
epoch:  14
accuracy train:  0.4575
accuracy: test 0.365
epoch:  15
accuracy train:  0.44875
accuracy: test 0.365
epoch:  16
accuracy train:  0.445
accuracy: test 0.335
epoch:  17
accuracy train:  0.44
accuracy: test 0.33
epoch:  

In [13]:
corrects, wrongs = CNN2.evaluate(train_imgs, train_labels)
print("accuracy train: ", corrects / ( corrects + wrongs))
corrects, wrongs = CNN2.evaluate(test_imgs, test_labels)
print("accuracy: test", corrects / ( corrects + wrongs))

cm = CNN.confusion_matrix(train_imgs, train_labels)
print(cm)

for i in range(10):
    print("digit: ", i, "precision: ", CNN.precision(i, cm), "recall: ", CNN.recall(i, cm))

accuracy train:  0.37625
accuracy: test 0.275
[[ 0  1  5  1  0  0  0  0  0  0]
 [ 0 93  9  1  4  7  5  1  5  1]
 [ 1  0  3  0  0  2  2  0  1  0]
 [ 8  0  0 20  3  6  0  0  0  0]
 [ 6  1 10  2  9  3  1  1  7  0]
 [ 1  0  1  2  1  5  1  1  1  0]
 [ 7  1 14  1 13 10 57  0  7 10]
 [31  1 27 32 39 26  4 83 42 70]
 [11  1  8  6  9  7  2  0  8  2]
 [14  0  4  8  3  6  1  0  2  1]]
digit:  0 precision:  0.0 recall:  0.0
digit:  1 precision:  0.9489795918367347 recall:  0.7380952380952381
digit:  2 precision:  0.037037037037037035 recall:  0.3333333333333333
digit:  3 precision:  0.273972602739726 recall:  0.5405405405405406
digit:  4 precision:  0.1111111111111111 recall:  0.225
digit:  5 precision:  0.06944444444444445 recall:  0.38461538461538464
digit:  6 precision:  0.7808219178082192 recall:  0.475
digit:  7 precision:  0.9651162790697675 recall:  0.23380281690140844
digit:  8 precision:  0.1095890410958904 recall:  0.14814814814814814
digit:  9 precision:  0.011904761904761904 recall:  0