In [1]:
import numpy as np
a = np.random.normal(0, 1, (2, 3,4))
a

array([[[ 0.02171538,  0.20065716, -0.83703331,  1.07455358],
        [ 1.59736856, -0.72695353,  1.04065838, -0.24171388],
        [-0.14639412, -0.98965458, -1.3913383 , -0.66503665]],

       [[ 1.45843319, -0.43069486, -0.47227544, -0.25416541],
        [ 0.71259689,  1.41356052, -1.77778981,  0.63387609],
        [ 0.45201807, -1.07633884,  0.64477448,  0.02390955]]])

In [2]:
print(3*5**2)


75


In [3]:
a = np.ones((4,4))
b = np.ones((3,3))

a.shape[1]
a@a

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [4]:
a[0:2,1:3]
np.sum(a)

16.0

In [5]:

def conv(input_image, cnn_kernel):
    """
    input_image,cnn_kernel,均是方阵
    """
    image_size = input_image.shape[0]
    kernel_size = cnn_kernel.shape[0]
    result_size = image_size - kernel_size + 1

    result = np.ones((result_size, result_size))
    for i in range(result_size):
        for j in range(result_size):
            result[i][j] = np.sum(input_image[i:i+kernel_size,j:j+kernel_size] * cnn_kernel)
    return result
conv(a,b)

array([[9., 9.],
       [9., 9.]])

In [6]:
def pool(input_image, pool_kernel):
    """
    input_image,pool_kernel必须有特定的维数，这里确定pool_kernel维数为2*2
    测试为正确

    """
    image_size = input_image.shape[0]
    kernel_size = pool_kernel.shape[0]
    result_size = image_size // 2  #要求必须能够整除,并且不能是float

    result = np.ones((result_size, result_size))
    for i in range(result_size):
        for j in range(result_size):
            
            result[i][j] = np.sum(input_image[i*kernel_size:(i+1)*kernel_size,j*kernel_size:(j+1)*kernel_size] * pool_kernel)
    return result
c = 1/2 *np.ones((2,2))
d = np.ones((8,8))
pool(d,c)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [19]:
a = [c, c]
np.array(a).shape
a[0][1]

array([0.5, 0.5])

In [8]:
a1 = [1,2,3,4,5,6,7,8,9,10, 11,12]
b1 = np.reshape(a1,(3,2,2))
c1 = np.reshape(b1,(-1,1))

In [9]:
b1

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [10]:
np.kron(np.eye(2),np.ones((2,1)))

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [11]:
c1.shape

(12, 1)

In [12]:
np.reshape(c1,(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [13]:
@np.vectorize
def sigmoid(inx):
    if inx>=0:      #对sigmoid函数的优化，避免了出现极大的数据溢出
        return 1.0/(1+np.exp(-inx))
    else:
        return np.exp(inx)/(1+np.exp(inx))

a2 = np.ones((4,2))
sigmoid(a2)

array([[0.73105858, 0.73105858],
       [0.73105858, 0.73105858],
       [0.73105858, 0.73105858],
       [0.73105858, 0.73105858]])

In [14]:
np.random.normal(0, 1,size=(1, 3))

array([[ 1.53114304, -0.23850813, -0.43708106]])

In [15]:
a = np.ones((2,2)) 
a @ a

array([[2., 2.],
       [2., 2.]])

In [16]:
1 -a

array([[0., 0.],
       [0., 0.]])

In [24]:
a4 = np.ones((2,3,4))
b4 = [a4, a4]
b4[0][1]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])