In [1]:
import numpy as np
image_size = 28 # width and length
no_of_different_labels = 10 #  i.e. 0, 1, 2, 3, ..., 9
image_pixels = image_size * image_size
data_path = "data/mnist/"
train_data = np.loadtxt(data_path + "mnist_train.csv", 
                        delimiter=",")
test_data = np.loadtxt(data_path + "mnist_test.csv", 
                       delimiter=",") 

In [2]:
train_data = train_data[:8000]
test_data = test_data[:2000]

In [3]:
fac = 0.99 / 255
train_imgs = np.asfarray(train_data[:, 1:]) * fac + 0.01
test_imgs = np.asfarray(test_data[:, 1:]) * fac + 0.01

train_labels = np.asfarray(train_data[:, :1])
test_labels = np.asfarray(test_data[:, :1])



lr = np.arange(no_of_different_labels)

# transform labels into one hot representation
train_labels_one_hot = (lr==train_labels).astype(float)
test_labels_one_hot = (lr==test_labels).astype(float)

# we don't want zeroes and ones in the labels neither:
train_labels_one_hot[train_labels_one_hot==0] = 0.01
train_labels_one_hot[train_labels_one_hot==1] = 0.99
test_labels_one_hot[test_labels_one_hot==0] = 0.01
test_labels_one_hot[test_labels_one_hot==1] = 0.99

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import nn

迭代准备

In [5]:
k=0
agent_number = 8
#初始化agent
ann_agent=[]
train_imgs_set=[]
train_labels_one_hot_set = []


for i in range(agent_number):
    ann_agent.append(nn.NeuralNetwork(no_of_in_nodes = image_pixels, 
                    no_of_out_nodes = 10, 
                    no_of_hidden_nodes = 100,
                    learning_rate = 0.1))
    train_imgs_set.append(train_imgs[1000*i : 1000*(i+1)])
    train_labels_one_hot_set.append(train_labels_one_hot[1000*i : 1000*(i+1)])
    
#初始化参数z，v_set

z, v = ann_agent[0].v_z_init_zero()

v_set = []
for i in range(agent_number):
    v_set.append(v)


In [6]:
#增广项的参数
c = 0.001
v_set[i][0].shape
[1,2] + [1,2]
len(train_imgs_set[i])

1000

In [8]:
#迭代次数
maxit = 50
#可能是训练的不够，加入epoch

epochs = 10

while(k<maxit):
    #训练agent更新weight
    for i in range(agent_number):
        #每个agent
        for j in range(len(train_imgs_set[i])):
            ann_agent[i].train_ture_admm(train_imgs_set[i][j], train_labels_one_hot_set[i][j], c, z, v_set[i]) #为了方便

        corrects, wrongs = ann_agent[i].evaluate(train_imgs, train_labels)
        print("迭代：", k, "agent", i,"accuracy train: ", corrects / ( corrects + wrongs))
        corrects, wrongs = ann_agent[i].evaluate(test_imgs, test_labels)
        print("迭代：", k, "agent", i,"accuracy: test", corrects / ( corrects + wrongs))

    #更新参数z
    #初始化temp
    temp = []  
    for i in range(len(z)):
        temp.append(np.zeros(z[i].shape))
    for i in range(agent_number):
        temp[0] += (ann_agent[i].wih + 1.0 / c*v_set[i][0]) #这个的维数是
        temp[1] += (ann_agent[i].who + 1.0 / c*v_set[i][1])
    temp[0] = temp[0] / agent_number
    temp[1] = temp[1] / agent_number 
    
    z = temp 
    
    #c更新v_set
    for i in range(agent_number):
        v_set[i][0] += c*(ann_agent[i].wih - z[0])
        v_set[i][1] += c*(ann_agent[i].who - z[1])
    
    k += 1

迭代： 0 agent 0 accuracy train:  0.287875
迭代： 0 agent 0 accuracy: test 0.2435
迭代： 0 agent 1 accuracy train:  0.20575
迭代： 0 agent 1 accuracy: test 0.1665
迭代： 0 agent 2 accuracy train:  0.266375
迭代： 0 agent 2 accuracy: test 0.2665
迭代： 0 agent 3 accuracy train:  0.1955
迭代： 0 agent 3 accuracy: test 0.1715
迭代： 0 agent 4 accuracy train:  0.099
迭代： 0 agent 4 accuracy: test 0.093
迭代： 0 agent 5 accuracy train:  0.210625
迭代： 0 agent 5 accuracy: test 0.2405
迭代： 0 agent 6 accuracy train:  0.09675
迭代： 0 agent 6 accuracy: test 0.0875
迭代： 0 agent 7 accuracy train:  0.12375
迭代： 0 agent 7 accuracy: test 0.119
迭代： 1 agent 0 accuracy train:  0.41075
迭代： 1 agent 0 accuracy: test 0.357
迭代： 1 agent 1 accuracy train:  0.284875
迭代： 1 agent 1 accuracy: test 0.255
迭代： 1 agent 2 accuracy train:  0.38625
迭代： 1 agent 2 accuracy: test 0.359
迭代： 1 agent 3 accuracy train:  0.237
迭代： 1 agent 3 accuracy: test 0.2045
迭代： 1 agent 4 accuracy train:  0.14875
迭代： 1 agent 4 accuracy: test 0.122
迭代： 1 agent 5 accuracy train:  0

迭代： 13 agent 5 accuracy: test 0.7585
迭代： 13 agent 6 accuracy train:  0.83925
迭代： 13 agent 6 accuracy: test 0.79
迭代： 13 agent 7 accuracy train:  0.779125
迭代： 13 agent 7 accuracy: test 0.721
迭代： 14 agent 0 accuracy train:  0.81475
迭代： 14 agent 0 accuracy: test 0.743
迭代： 14 agent 1 accuracy train:  0.85025
迭代： 14 agent 1 accuracy: test 0.792
迭代： 14 agent 2 accuracy train:  0.785625
迭代： 14 agent 2 accuracy: test 0.7455
迭代： 14 agent 3 accuracy train:  0.856875
迭代： 14 agent 3 accuracy: test 0.8085
迭代： 14 agent 4 accuracy train:  0.75675
迭代： 14 agent 4 accuracy: test 0.7015
迭代： 14 agent 5 accuracy train:  0.836125
迭代： 14 agent 5 accuracy: test 0.776
迭代： 14 agent 6 accuracy train:  0.845375
迭代： 14 agent 6 accuracy: test 0.799
迭代： 14 agent 7 accuracy train:  0.7855
迭代： 14 agent 7 accuracy: test 0.7285
迭代： 15 agent 0 accuracy train:  0.824625
迭代： 15 agent 0 accuracy: test 0.7535
迭代： 15 agent 1 accuracy train:  0.856
迭代： 15 agent 1 accuracy: test 0.799
迭代： 15 agent 2 accuracy train:  0.8525
迭代： 1

迭代： 27 agent 0 accuracy train:  0.126875
迭代： 27 agent 0 accuracy: test 0.1495
迭代： 27 agent 1 accuracy train:  0.126875
迭代： 27 agent 1 accuracy: test 0.1495
迭代： 27 agent 2 accuracy train:  0.126875
迭代： 27 agent 2 accuracy: test 0.1495
迭代： 27 agent 3 accuracy train:  0.126875
迭代： 27 agent 3 accuracy: test 0.1495
迭代： 27 agent 4 accuracy train:  0.126875
迭代： 27 agent 4 accuracy: test 0.1495
迭代： 27 agent 5 accuracy train:  0.126875
迭代： 27 agent 5 accuracy: test 0.1495
迭代： 27 agent 6 accuracy train:  0.126875
迭代： 27 agent 6 accuracy: test 0.1495
迭代： 27 agent 7 accuracy train:  0.126875
迭代： 27 agent 7 accuracy: test 0.1495
迭代： 28 agent 0 accuracy train:  0.114875
迭代： 28 agent 0 accuracy: test 0.1345
迭代： 28 agent 1 accuracy train:  0.114875
迭代： 28 agent 1 accuracy: test 0.1345
迭代： 28 agent 2 accuracy train:  0.114875
迭代： 28 agent 2 accuracy: test 0.1345
迭代： 28 agent 3 accuracy train:  0.114875
迭代： 28 agent 3 accuracy: test 0.1345
迭代： 28 agent 4 accuracy train:  0.114875
迭代： 28 agent 4 accuracy

迭代： 40 agent 1 accuracy: test 0.1345
迭代： 40 agent 2 accuracy train:  0.114875
迭代： 40 agent 2 accuracy: test 0.1345
迭代： 40 agent 3 accuracy train:  0.114875
迭代： 40 agent 3 accuracy: test 0.1345
迭代： 40 agent 4 accuracy train:  0.114875
迭代： 40 agent 4 accuracy: test 0.1345
迭代： 40 agent 5 accuracy train:  0.114875
迭代： 40 agent 5 accuracy: test 0.1345
迭代： 40 agent 6 accuracy train:  0.114875
迭代： 40 agent 6 accuracy: test 0.1345
迭代： 40 agent 7 accuracy train:  0.114875
迭代： 40 agent 7 accuracy: test 0.1345
迭代： 41 agent 0 accuracy train:  0.126875
迭代： 41 agent 0 accuracy: test 0.1495
迭代： 41 agent 1 accuracy train:  0.126875
迭代： 41 agent 1 accuracy: test 0.1495
迭代： 41 agent 2 accuracy train:  0.126875
迭代： 41 agent 2 accuracy: test 0.1495
迭代： 41 agent 3 accuracy train:  0.126875
迭代： 41 agent 3 accuracy: test 0.1495
迭代： 41 agent 4 accuracy train:  0.126875
迭代： 41 agent 4 accuracy: test 0.1495
迭代： 41 agent 5 accuracy train:  0.126875
迭代： 41 agent 5 accuracy: test 0.1495
迭代： 41 agent 6 accuracy tra

In [10]:
numb = 1
corrects, wrongs = ann_agent[numb].evaluate(train_imgs, train_labels)
print("accuracy train: ", corrects / ( corrects + wrongs))
corrects, wrongs = ann_agent[numb].evaluate(test_imgs, test_labels)
print("accuracy: test", corrects / ( corrects + wrongs))

cm = ann_agent[numb].confusion_matrix(train_imgs, train_labels)
print(cm)

for i in range(10):
    print("digit: ", i, "precision: ", ann_agent[numb].precision(i, cm), "recall: ", ann_agent[numb].recall(i, cm))

accuracy train:  0.126875
accuracy: test 0.1495
[[325 360 389 209 303 184 334  89 323 140]
 [119 225  99 117 111 163 179 348 228 219]
 [  0   0   0   1   2   0   0   1   2   0]
 [ 25  73  70 122  40  63  51  36  71  35]
 [324 245 224 362 341 291 233 379 127 399]
 [  0   0   0   0   0   0   0   0   0   0]
 [  2   2   6   0   2   1   1   0   1   2]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   0   0   0   0]]
digit:  0 precision:  0.4088050314465409 recall:  0.1223644578313253
digit:  1 precision:  0.24834437086092714 recall:  0.12444690265486726
digit:  2 precision:  0.0 recall:  0.0
digit:  3 precision:  0.1504315659679408 recall:  0.20819112627986347
digit:  4 precision:  0.4267834793491865 recall:  0.11658119658119658
digit:  5 precision:  0.0 recall:  nan
digit:  6 precision:  0.0012531328320802004 recall:  0.058823529411764705
digit:  7 precision:  0.0 recall:  nan
digit:  8 precision:  0.0013280212483399733 recall

In [13]:
i = 1
j = i + 1
print("wih_error: \n",ann_agent[i].wih - ann_agent[j].wih)
print("who_error: \n",ann_agent[i].who - ann_agent[j].who)

wih_error: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
who_error: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0